CREATE TABLE Worker (
    WORKER_ID INT PRIMARY KEY,
    FIRST_NAME CHAR(25) NOT NULL,
    LAST_NAME CHAR(25),
    SALARY INT CHECK (SALARY BETWEEN 10000 AND 25000),
    JOINING_DATE DATETIME,
    DEPARTMENT CHAR(25) CHECK (DEPARTMENT IN ('HR', 'Sales', 'Accts', 'IT'))
);

INSERT INTO Worker VALUES
(1, 'Amitabh', 'Singh', 20000, '2016-06-11 00:00:00', 'HR'),
(2, 'Vipul', 'Sharma', 15000, '2014-02-10 00:00:00', 'Sales'),
(3, 'Satish', 'Kumar', 18000, '2014-02-15 00:00:00', 'IT'),
(4, 'Rahul', 'Verma', 22000, '2015-07-20 00:00:00', 'Accts');

-Q1-  
SELECT FIRST_NAME AS WORKER_NAME FROM Worker;

-Q2-
SELECT UPPER(FIRST_NAME) FROM Worker;

-Q3-
SELECT DISTINCT DEPARTMENT FROM Worker;

-Q4-
SELECT SUBSTRING(FIRST_NAME, 1, 3) FROM Worker;

-Q5-
SELECT INSTR(FIRST_NAME, 'a') 
FROM Worker 
WHERE FIRST_NAME = 'Amitabh';

-Q6-
SELECT RTRIM(FIRST_NAME) FROM Worker;

-Q7-
SELECT LTRIM(DEPARTMENT) FROM Worker;

-Q8-
SELECT DISTINCT DEPARTMENT, LENGTH(DEPARTMENT) 
FROM Worker;

-Q9-
SELECT REPLACE(FIRST_NAME, 'a', 'A') FROM Worker;

-Q10-
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS COMPLETE_NAME 
FROM Worker;

-Q11-
SELECT * FROM Worker 
ORDER BY FIRST_NAME ASC;

-Q12-
SELECT * FROM Worker 
ORDER BY FIRST_NAME ASC, DEPARTMENT DESC;

-Q13-
SELECT * FROM Worker 
WHERE FIRST_NAME IN ('Vipul', 'Satish');

-Q14-
SELECT * FROM Worker 
WHERE FIRST_NAME NOT IN ('Vipul', 'Satish');

-Q15-
SELECT * FROM Worker 
WHERE DEPARTMENT = 'Admin';
HR, Sales, Accts, IT
  
-Q16-
SELECT * FROM Worker 
WHERE FIRST_NAME LIKE '%a%';

-Q17-
SELECT * FROM Worker 
WHERE FIRST_NAME LIKE '%a';

-Q18-
SELECT * FROM Worker 
WHERE FIRST_NAME LIKE '_____h';

-Q19-
SELECT * FROM Worker 
WHERE SALARY BETWEEN 100000 AND 500000;

-Q20-
SELECT * FROM Worker 
WHERE YEAR(JOINING_DATE) = 2014 
AND MONTH(JOINING_DATE) = 2;

-Q21-
SELECT COUNT(*) 
FROM Worker 
WHERE DEPARTMENT = 'Admin';
